schema:
  - https://cms.basso-yanity.com/graphql
generates:
  ./graphql.ts:
    plugins:
      - 'typescript'
      - 'typescript-operations'
      - 'typescript-react-apollo'
      - 'fragment-matcher'
    config:
      withRefetchFn: true
